[project]
name = "garimpo"
version = "0.1.0"
description = ""
authors = [
    {name = "santana",email = "sannt11na@sempreceub.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx (>=0.28.1,<0.29.0)",
    "pandas (>=2.2,<3.0)",
    "streamlit (>=1.53.1,<2.0.0)",
    "sqlalchemy (>=2.0.46,<3.0.0)",
    "pydantic (>=2.12.5,<3.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "python-telegram-bot (>=22.6,<23.0)",
    "selenium (>=4.40.0,<5.0.0)"
]

[tool.poetry]
packages = [{include = "garimpo", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
